import { useDispatch } from "react-redux";
import Head from 'next/head';
// import axios from 'axios';

import { withLayout } from "../layout/Layout";

import Hero from '../components/Hero/Hero';
import WhatWeDo from '../components/WhatWeDo/WhatWeDo';
import WhyChooseUs from '../components/WhyChooseUs/WhyChooseUs';

import Subscribe from '../components/Form/Subscribe';

const Home = ({ }) => {
	return (
		<>
			<Head>
				<title>Mechanics Vancouver</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Hero />
			{/* <Filter /> */}
			<WhatWeDo />
			<WhyChooseUs />
			<Subscribe />
		</>
	)
};


export const getStaticProps = async () => {
	// const {data: hero} = await axios.get(getMovieByName('Puss in Boots: The Last Wish'));
	// const {data: movies} = await axios.get(getMovie(1));

	// if(!hero && !movies){
	// 	return{
	// 		notFound: true
	// 	}
	// }

	return {
		props: {
			// HeroSsrFetch: hero.results[0],
			// MoviesSsrFetch: movies.results
		}
	}
}

export default withLayout(Home);
